services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_libros
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "S0luc10nPrueb4!"
    volumes:
      - ./database:/database
      - ./docker/init-db.sh:/init-db.sh
    entrypoint: [ "/bin/bash", "/init-db.sh" ]
